# Generated by Django 3.2.7 on 2023-04-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
